version: "3"
services:
  asm_unicom:
    container_name: asm_unicom
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/AutoSignMachine #同步脚本地址
    restart: always
    tty: true
    network_mode: "bridge"
    hostname: asm_unicom
    extra_hosts:
      - "github.com:13.229.188.59"
      - "raw.githubusercontent.com:151.101.228.133"
    environment:
      - enable_unicom=true #签到开关 false / true
      - user= # 输入用户手机号
      - password= #输入用户密码
      - appid= #输入手机端APPID
      - notify_sctkey=
  # asm_bili:
  #   container_name: asm_bili
  #   build:
  #     context: ./
  #     dockerfile: docker/Dockerfile
  #   volumes:
  #     - ./:/AutoSignMachine #同步脚本地址
  #   restart: always
  #   tty: true
  #   network_mode: "bridge"
  #   environment:
  #     - enable_bilibili=false #签到开关
  #     - DedeUserID= #
  #     - SESSDATA= #
  #     - bili_jct= #

  # asm52pojie:
  #   container_name: asm52pojie
  #   build:
  #     context: ./
  #     dockerfile: docker/Dockerfile
  #   volumes:
  #     - ./:/AutoSignMachine #同步脚本地址
  #   restart: always
  #   tty: true
  #   network_mode: "bridge"
  #   environment:
  #     - enable_52pojie=false #签到开关
  #     - htVD_2132_auth= #
  #     - htVD_2132_saltkey= #

  # asm_iqiyi:
  #   container_name: asm_iqiyi
  #   build:
  #     context: ./
  #     dockerfile: docker/Dockerfile
  #   volumes:
  #     - ./:/AutoSignMachine #同步脚本地址
  #   restart: always
  #   tty: true
  #   network_mode: "bridge"
  #   environment:
  #     - enable_iqiyi=false #签到开关
  #     - P00001= #
  #     - P00PRU= #
  #     - QC005= #
  #     - dfp= #

